#!/usr/bin/env bash

shopt -s nullglob globstar

source ~/.zshrc
prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | /home/matt/.fzf/bin/fzf "$@")

[[ -n $password ]] || exit

tmux send-keys -t notes:passfzf "pass show -c $password" C-m
